import type { QueueItemType } from "@/types/QueueItemType";

export const queueData: QueueItemType[] = [
  {
    id: "1",
    title: "Inception",
    type: "movie",
    description:
      "A thief who steals corporate secrets through dream-sharing technology.",
    year: 2010,
    rating: 8.8,
    size: "2.1 GB",
    quality: "1080p",
    image: "/images/inception.jpg",
    downloadUrl: "https://example.com/inception",
    status: "downloading",
    progress: 65,
    downloadSpeed: "5.2 MB/s",
    estimatedTime: "va calcolato",
    addedAt: new Date("2024-01-20T10:30:00"),
    tmdbId: "1",
  },
  {
    id: "2",
    title: "Breaking Bad - Stagione 1",
    type: "series",
    description: "A high school chemistry teacher turned methamphetamine cook.",
    year: 2008,
    rating: 9.5,
    seasons: 5,
    size: "8.5 GB",
    quality: "720p",
    image: "/images/breaking-bad.jpg",
    downloadUrl: "https://example.com/breaking-bad-s1",
    status: "pending",
    addedAt: new Date("2024-01-20T11:15:00"),
    tmdbId: "2",
  },
  {
    id: "3",
    title: "Attack on Titan",
    type: "anime",
    description: "Humanity fights for survival against giant humanoid Titans.",
    year: 2013,
    rating: 9.0,
    seasons: 4,
    size: "12.3 GB",
    quality: "1080p",
    image: "/images/attack-on-titan.jpg",
    downloadUrl: "https://example.com/attack-on-titan",
    status: "pending",
    addedAt: new Date("2024-01-20T12:00:00"),
    tmdbId: "3",
  },
  {
    id: "4",
    title: "Our Planet",
    type: "documentary",
    description:
      "Experience our planet's natural beauty and examine how climate change impacts all living creatures.",
    year: 2019,
    rating: 9.3,
    size: "4.7 GB",
    quality: "4K",
    image: "/images/our-planet.jpg",
    downloadUrl: "https://example.com/our-planet",
    status: "completed",
    progress: 100,
    addedAt: new Date("2024-01-20T09:45:00"),
    tmdbId: "4",
  },
  {
    id: "5",
    title: "The Matrix",
    type: "movie",
    description:
      "A computer programmer discovers that reality as he knows it is a simulation.",
    year: 1999,
    rating: 8.7,
    size: "1.8 GB",
    quality: "1080p",
    image: "/images/matrix.jpg",
    downloadUrl: "https://example.com/matrix",
    status: "error",
    addedAt: new Date("2024-01-20T13:30:00"),
    errorCode: "SC-001",
    tmdbId: "5",
  },
];
