import type { QueueItemType } from "@/types/QueueItemType";

export const queueData: QueueItemType[] = [
  {
    id: "tmdb_27205",
    type: "movie",
    size: "1 GB",
    quality: "1080p",
    downloadUrl: "https://example.com/download",
    tmdbId: "27205",
    title: "Inception",
    adult: false,
    poster_path: "/7NCFUxQNExfxd0kmkTqIwd1cMol.jpg",
    original_title: "Inception",
    original_language: "en",
    original_country: ["GB", "US"],
    rating: 8.37,
    genres: ["Azione", "Fantascienza", "Avventura"],
    description:
      "Dom Cobb possiede una qualifica speciale: è in grado di inserirsi nei sogni altrui per prelevare i segreti nascosti nel più profondo del subconscio. Viene contattato da Saito, un potentissimo industriale di origine giapponese, il quale gli chiede di tentare l'operazione opposta. Non deve prelevare pensieri celati ma inserire un'idea che si radichi nella mente di una persona. Costui è Robert Fischer Jr. il quale, alla morte dell'anziano e dittatoriale genitore, dovrà convincersi che l'unica cosa che può fare è distruggere l'impero ereditato. Saito avrà allora campo libero. In cambio offrirà a Cobb la possibilità di rientrare negli Stati Uniti dove è ricercato per omicidio. Cobb accetta e si fa affiancare da un team di cui entra a far parte la giovane Ariane, architetto abilissimo nella costruzione di spazi virtuali.",
    year: 2010,
    release_date: "2010-07-15",
    duration: 148,

    status: "downloading",
    progress: 65,
    downloadSpeed: "5.2 MB/s",
    estimatedTime: "va calcolato",
    addedAt: new Date("2024-01-20T10:30:00"),
  },
  {
    id: "2",
    title: "Breaking Bad - Stagione 1",
    type: "series",
    year: 2008,
    seasons: 5,
    size: "8.5 GB",
    quality: "720p",
    downloadUrl: "https://example.com/breaking-bad-s1",
    status: "pending",
    addedAt: new Date("2024-01-20T11:15:00"),
    tmdbId: "2",
  },
  {
    id: "3",
    title: "Attack on Titan",
    type: "anime",
    year: 2013,
    seasons: 4,
    size: "12.3 GB",
    quality: "1080p",
    downloadUrl: "https://example.com/attack-on-titan",
    status: "pending",
    addedAt: new Date("2024-01-20T12:00:00"),
    tmdbId: "3",
  },
  {
    id: "4",
    title: "Our Planet",
    type: "movie",
    year: 2019,
    size: "4.7 GB",
    quality: "4K",
    downloadUrl: "https://example.com/our-planet",
    status: "completed",
    progress: 100,
    addedAt: new Date("2024-01-20T09:45:00"),
    tmdbId: "4",
  },
  {
    id: "tmdb_603",
    type: "movie",
    size: "1 GB",
    quality: "1080p",
    downloadUrl: "https://example.com/download",
    tmdbId: "603",
    title: "Matrix",
    adult: false,
    poster_path: "/yQZX4scmfYtj4ccKFNGZJlOj1y9.jpg",
    original_title: "The Matrix",
    original_language: "en",
    original_country: ["US"],
    rating: 8.237,
    genres: ["Azione", "Fantascienza"],
    description:
      "Seguendo un tatuaggio sulla spalla di una ragazza, l'hacker Neo scopre che la cosiddetta \"realtà\" è solo un impulso elettrico fornito al cervello degli umani da un'intelligenza artificiale. Per sopravvivere alla catastrofe l'umanità ha infatti avuto bisogno delle macchine, ma queste hanno vinto e necessitano degli uomini come fonte di energia. L'illusione in cui li fanno vivere è quindi finalizzata a \"coltivarli\" meglio. Nessuno è a conoscenza del tempo che è passato da quando il neurosimulatore ha assegnato una data fittizia al tempo. Solo Neo, con l'aiuto del pirata informatico Morpheus e della bella Trinity, può tentare di scoprire la verità, ma non sarà un'impresa facile.",
    year: 1999,
    release_date: "1999-03-31",
    duration: 136,

    status: "error",
    addedAt: new Date("2024-01-20T13:30:00"),
    errorCode: "SC-001",
  },
];
