import type { MediaItemType } from "@/types/MediaItemType";

export const mediaItems: MediaItemType[] = [
  {
    id: "1",
    title: "Inception",
    type: "movie",
    year: 2010,
    rating: 8.8,
    duration: "2h 28min",
    size: "2.1 GB",
    quality: "1080p",
    downloadUrl: "https://example.com/inception",
    tmdbId: "1",
  },
  {
    id: "2",
    title: "Breaking Bad",
    type: "series",
    year: 2008,
    rating: 9.5,
    seasons: 5,
    size: "45.2 GB",
    quality: "1080p",
    downloadUrl: "https://example.com/breaking-bad",
    tmdbId: "2",
  },
  {
    id: "3",
    title: "Attack on Titan",
    type: "anime",
    year: 2013,
    rating: 9.0,
    seasons: 4,
    size: "28.5 GB",
    quality: "1080p",
    downloadUrl: "https://example.com/attack-on-titan",
    tmdbId: "3",
  },
  {
    id: "4",
    title: "Planet Earth II",
    type: "movie",
    year: 2016,
    rating: 9.5,
    duration: "6h 0min",
    size: "15.8 GB",
    quality: "4K",
    downloadUrl: "https://example.com/planet-earth",
    tmdbId: "4",
  },
  {
    id: "5",
    title: "The Dark Knight",
    type: "movie",
    year: 2008,
    rating: 9.0,
    duration: "2h 32min",
    size: "2.8 GB",
    quality: "1080p",
    downloadUrl: "https://example.com/dark-knight",
    tmdbId: "5",
  },
  {
    id: "6",
    title: "Stranger Things",
    type: "series",
    year: 2016,
    rating: 8.7,
    seasons: 4,
    size: "32.1 GB",
    quality: "4K",
    downloadUrl: "https://example.com/stranger-things",
    tmdbId: "6",
  },
];
