import type { MediaItemType } from "@/types/MediaItemType";

export const mediaItems: MediaItemType[] = [
  {
    id: "tmdb_27205",
    type: "movie",
    size: "1 GB",
    quality: "1080p",
    downloadUrl: "https://example.com/download",
    tmdbId: "27205",
    title: "Inception",
    adult: false,
    poster_path: "/7NCFUxQNExfxd0kmkTqIwd1cMol.jpg",
    original_title: "Inception",
    original_language: "en",
    original_country: ["GB", "US"],
    rating: 8.37,
    genres: ["Azione", "Fantascienza", "Avventura"],
    description:
      "Dom Cobb possiede una qualifica speciale: è in grado di inserirsi nei sogni altrui per prelevare i segreti nascosti nel più profondo del subconscio. Viene contattato da Saito, un potentissimo industriale di origine giapponese, il quale gli chiede di tentare l'operazione opposta. Non deve prelevare pensieri celati ma inserire un'idea che si radichi nella mente di una persona. Costui è Robert Fischer Jr. il quale, alla morte dell'anziano e dittatoriale genitore, dovrà convincersi che l'unica cosa che può fare è distruggere l'impero ereditato. Saito avrà allora campo libero. In cambio offrirà a Cobb la possibilità di rientrare negli Stati Uniti dove è ricercato per omicidio. Cobb accetta e si fa affiancare da un team di cui entra a far parte la giovane Ariane, architetto abilissimo nella costruzione di spazi virtuali.",
    year: 2010,
    release_date: "2010-07-15",
    duration: 148,
  },
  {
    id: "tmdb_1396",
    type: "series",
    size: "1 GB",
    quality: "1080p",
    downloadUrl: "https://example.com/download",
    tmdbId: "1396",
    title: "Breaking Bad",
    adult: false,
    poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    original_title: "Breaking Bad",
    original_language: "en",
    original_country: ["US"],
    rating: 8.936,
    genres: ["Dramma", "Crime"],
    description:
      "Un insegnante di chimica con un cancro allo stadio terminale comincia a produrre e spacciare metanfetamina con un suo ex studente per assicurare un futuro alla famiglia.",
    year: 2008,
    first_air_date: "2008-01-20",
    last_air_date: "2013-09-29",
    episode_run_time: [],
    number_of_seasons: 5,
    number_of_episodes: 62,
    in_production: false,
    languages: ["en", "de", "es"],
    seasons: [
      {
        id: 3577,
        name: "Speciali",
        description: "",
        season_number: 0,
        episode_count: 9,
        air_date: "2009-02-17",
        poster_path: "/4RaIvSQgHHHPfaI1jFqaMR8UJWM.jpg",
      },
      {
        id: 3572,
        name: "Stagione 1",
        description:
          "Dopo la diagnosi di una malattia terminale, un insegnante delle superiori si dedica alla produzione e allo spaccio di droga per assicurare un futuro agiato alla famiglia.",
        season_number: 1,
        episode_count: 7,
        air_date: "2008-01-20",
        poster_path: "/rqMhs1v6HdaT9NQMlR2TgjKhbNF.jpg",
      },
      {
        id: 3573,
        name: "Stagione 2",
        description:
          "Improvvisatosi spacciatore, un insegnante si fa un nome nel giro della droga e attira l'attenzione dei cartelli rivali, mettendo a rischio la vita dei suoi cari.",
        season_number: 2,
        episode_count: 13,
        air_date: "2009-03-08",
        poster_path: "/f8BvSJPGtNYLXsYwRUvCrnwrSRS.jpg",
      },
      {
        id: 3575,
        name: "Stagione 3",
        description:
          "Nonostante la sua precaria situazione al termine della stagione precedente, Walter White continua a produrre e spacciare droga per il bene della famiglia.",
        season_number: 3,
        episode_count: 13,
        air_date: "2010-03-21",
        poster_path: "/vnuXj0Q8A2xYvkyqxtWquqGrQOm.jpg",
      },
      {
        id: 3576,
        name: "Stagione 4",
        description:
          "Il premio Emmy Bryan Cranston torna a interpretare Walter White, un insegnante che comincia a produrre metanfetamina, facendo concorrenza al boss Gus Fring.",
        season_number: 4,
        episode_count: 13,
        air_date: "2011-07-17",
        poster_path: "/6kpXSb6Re7HoFLzgyZ0nHmDL9hb.jpg",
      },
      {
        id: 3578,
        name: "Stagione 5",
        description:
          "Nella stagione conclusiva, Walt non deve più fingere di essere cattivo: il declino morale che lo ha portato a capo di un impero della droga è diventato realtà.",
        season_number: 5,
        episode_count: 16,
        air_date: "2012-07-15",
        poster_path: "/j9zVQyEuQrRlDJPS6kW0bkZppqc.jpg",
      },
    ],
  },
  {
    id: "tmdb_1429",
    type: "series",
    size: "1 GB",
    quality: "1080p",
    downloadUrl: "https://example.com/download",
    tmdbId: "1429",
    title: "L'attacco dei giganti",
    adult: false,
    poster_path: "/b89Hz9HA65dXqX7grKilqNCWWj5.jpg",
    original_title: "進撃の巨人",
    original_language: "ja",
    original_country: ["JP"],
    rating: 8.7,
    genres: ["Animazione", "Sci-Fi & Fantasy", "Action & Adventure"],
    description:
      "Diverse centinaia di anni fa, la razza umana fu quasi sterminata dai giganti. Si racconta di quanto questi fossero alti, privi di intelligenza e affamati di carne umana; peggio ancora, essi sembra divorassero umani più per piacere che per necessario sostentamento. Una piccola percentuale dell'umanità però sopravvisse asserragliandosi in una città circondata da mura estremamente alte, anche più alte del più grande di giganti. Eren è un adolescente che vive in questa città, dove non si vede un gigante da oltre un secolo. Ma presto un orrore indicibile si palesa alle sue porte, ed un gigante più grande di quanto si sia mai sentito narrare, appare dal nulla abbattendo le mura ed imperversando assieme ad altri suoi simili fra la popolazione. Eren, vinto il terrore iniziale, si ripromette di eliminare ogni singolo gigante, per vendicare l'umanità tutta.",
    year: 2013,
    first_air_date: "2013-04-07",
    last_air_date: "2022-04-04",
    episode_run_time: [],
    number_of_seasons: 4,
    number_of_episodes: 87,
    in_production: false,
    languages: ["ja"],
    seasons: [
      {
        id: 3789,
        name: "Speciali",
        description: "",
        season_number: 0,
        episode_count: 37,
        air_date: "2013-07-07",
        poster_path: "/7wWCu9llAFcMjWs8Y9W8E4W8p6.jpg",
      },
      {
        id: 3788,
        name: "Stagione 1",
        description:
          "Secoli fa, l'umanità fu massacrata fino quasi all'estinzione da mostruose creature umanoidi chiamate giganti, costringendo gli umani a nascondersi nella paura dietro enormi mura concentriche. Ciò che rende questi giganti davvero terrificanti è che il loro gusto per la carne umana non nasce dalla fame, ma da ciò che sembra essere dal piacere. Per garantire la loro sopravvivenza, i resti dell'umanità hanno iniziato a vivere all'interno di barriere difensive, risultando in cento anni senza un singolo incontro con i giganti. Tuttavia, quella fragile calma viene presto infranta quando un colossale gigante riesce a fare breccia nel presunto muro esterno inespugnabile, riaccendendo la lotta per la sopravvivenza contro gli abomini mangia-uomini.",
        season_number: 1,
        episode_count: 25,
        air_date: "2013-04-07",
        poster_path: "/xUbqpYnFYvWRIypsf2y2l8ZrPyM.jpg",
      },
      {
        id: 84756,
        name: "Stagione 2",
        description:
          "Eren Yeager e altri del 104° Corpo di Addestramento Reclute hanno appena iniziato a diventare membri a pieno titolo del Armata Ricognitiva. Mentre si preparano ad affrontare ancora una volta i giganti, vengono interrotti dall'invasione del Wall Rose, ma non tutto è come sembra poiché altri misteri vengono svelati. Mentre l'Armata Ricognitiva corre per chiudere il muro, scoprono di più sui giganti invasori e sugli oscuri segreti dello stato.",
        season_number: 2,
        episode_count: 12,
        air_date: "2017-04-01",
        poster_path: "/hpA2jkufYf7u6xJCs1OAZ1Bo9Ox.jpg",
      },
      {
        id: 98013,
        name: "Stagione 3",
        description:
          "Eren ei suoi compagni nella 104° sono assegnati alla neonata Squadra Levi, il cui compito è quello di mantenere Eren e Historia al sicuro. Levi ed Erwin hanno buone ragioni di essere preoccupati perché il sacerdote della Chiesa che Hange aveva nascosto è stato trovato torturato a morte, mettendo in chiaro che la polizia militare è coinvolta nell'insabbiamento. Le cose si fanno più strazianti quando i parlamentari si rifanno su Erwin e la Squadra Levi evita per un pelo la cattura. Eren ha anche problemi con la sua trasformazione, e un assassino mortale, vecchia conoscenza di levi, è stato assunto per rapire Eren e Historia.",
        season_number: 3,
        episode_count: 22,
        air_date: "2018-07-23",
        poster_path: "/a3Bkgx4ScL5aPJxZVxhGMpyzqoW.jpg",
      },
      {
        id: 126952,
        name: "La Stagione Finale",
        description:
          "La verità rivelata dai ricordi di Eren e dai diari di Grisha scuote tutte le convinzioni più profonde di Eren. Al contrario die quello che veniva insegnato oltre le mura c'è tutto un altro mondo, ugualmente pieno di oppressione e di guerra. Improvvisamente, le ambizioni che animano da generazioni la Armata Ricognitiva sembrano piccole e ingenue. Cosa resta per cui combattere?",
        season_number: 4,
        episode_count: 28,
        air_date: "2020-12-07",
        poster_path: "/y9ia0JU8DTRml9vDa5L2DRrrbw9.jpg",
      },
    ],
  },
  {
    id: "tmdb_596683",
    type: "movie",
    size: "1 GB",
    quality: "1080p",
    downloadUrl: "https://example.com/download",
    tmdbId: "596683",
    title: "Planet Earth II: A World of Wonder",
    adult: false,
    poster_path: "/qV9T4ORVpwgF5e2BPy5Ev7v8UWj.jpg",
    original_title: "Planet Earth II: A World of Wonder",
    original_language: "en",
    original_country: ["GB"],
    rating: 7.4,
    genres: ["Documentario"],
    description: "",
    year: 2017,
    release_date: "2017-01-01",
    duration: 89,
  },
  {
    id: "tmdb_123025",
    type: "movie",
    size: "1 GB",
    quality: "1080p",
    downloadUrl: "https://example.com/download",
    tmdbId: "123025",
    title: "Batman: The Dark Knight Returns, Part 1",
    adult: false,
    poster_path: "/7yAPPLZpTnPN7qb1qSCNuotQpew.jpg",
    original_title: "Batman: The Dark Knight Returns, Part 1",
    original_language: "en",
    original_country: ["US"],
    rating: 7.7,
    genres: ["Fantascienza", "Azione", "Animazione", "Mistero"],
    description:
      "Batman è sparito dalla circolazione da dieci anni. Nel frattempo, una nuova stirpe di criminali sta terrorizzando Gotham City, convincendo il cinquantacinquenne Bruce a tornare ad assumere l'identità del supereroe. Ma Batman ha davvero ciò che serve per combattere il crimine in una nuova era?",
    year: 2012,
    release_date: "2012-09-25",
    duration: 76,
  },
  {
    id: "tmdb_66732",
    type: "series",
    size: "1 GB",
    quality: "1080p",
    downloadUrl: "https://example.com/download",
    tmdbId: "66732",
    title: "Stranger Things",
    adult: false,
    poster_path: "/wZNIKNMqjulcU1AbU6X98tHy9QF.jpg",
    original_title: "Stranger Things",
    original_language: "en",
    original_country: ["US"],
    rating: 8.581,
    genres: ["Sci-Fi & Fantasy", "Mistero", "Action & Adventure"],
    description:
      "La scomparsa di un ragazzino in una cittadina porta alla luce un mistero in cui si mescolano esperimenti segreti, spaventose forze soprannaturali e una strana bambina.",
    year: 2016,
    first_air_date: "2016-07-15",
    last_air_date: "2025-12-31",
    episode_run_time: [],
    number_of_seasons: 5,
    number_of_episodes: 42,
    in_production: false,
    languages: ["en"],
    seasons: [
      {
        id: 77680,
        name: "Stagione 1",
        description:
          "Succedono strane cose a Hawkins nell'Indiana, dove l'improvvisa scomparsa di un ragazzino porta alla luce una coetanea dai poteri ultraterreni.",
        season_number: 1,
        episode_count: 8,
        air_date: "2016-07-15",
        poster_path: "/z8DLww0xT1upKOsMMRqQkh4BJOV.jpg",
      },
      {
        id: 83248,
        name: "Stagione 2",
        description:
          "È trascorso un anno dalla strana scomparsa di Will, ma a Hawkins la vita non è ancora tornata alla normalità... neanche lontanamente.",
        season_number: 2,
        episode_count: 9,
        air_date: "2017-10-27",
        poster_path: "/d4XRUgUhyY6JMBZhSgUW3MyIEyC.jpg",
      },
      {
        id: 115216,
        name: "Stagione 3",
        description:
          "Nuovi amori, un moderno centro commerciale e ratti con la rabbia che corrono verso il pericolo. Hawkins, 1985: è arrivata l'estate. E in una stagione tutto può cambiare.",
        season_number: 3,
        episode_count: 8,
        air_date: "2019-07-04",
        poster_path: "/rdVSNg7Dk3r6oHIEjYeJJ9aB40e.jpg",
      },
      {
        id: 163313,
        name: "Stagione 4",
        description:
          "Il male torna a Hawkins giusto in tempo per le vacanze di primavera e porta con sé un rinnovato terrore, ricordi inquietanti e una nuova sinistra minaccia.",
        season_number: 4,
        episode_count: 9,
        air_date: "2022-05-27",
        poster_path: "/7RGdJREN8Iw8HWl6T7zgwlkY1XC.jpg",
      },
      {
        id: 402292,
        name: "Stagione 5",
        description: "",
        season_number: 5,
        episode_count: 8,
        air_date: "2025-11-26",
        poster_path: "/smJLpfNldCFKJoj7oN4yakbV9ga.jpg",
      },
    ],
  },
];
